name = "gleam_community_maths"
version = "0.1.0"

licences = ["Apache-2.0"]
description = "A basic maths library"
repository = { type = "github", user = "gleam-community", repo = "maths" }

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.7"
