name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: "26.0.2"
          gleam-version: "0.30.5"
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.1"
      - run: gleam format --check src test
      - run: gleam test --target erlang
      - run: gleam test --target javascript